language: go

go:
  - 1.10.x
  - 1.12.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - 1.17.x

before_install:
  - apt-get update && apt-get install --reinstall ca-certificates
  - go get -v github.com/snower/slock

script:
  - ./run-tests