#!/bin/bash

log_error() {
  echo "$*" 1>&2
}

run_govet() {
    GOVET_ERRORS=$(go vet "$*" 2>&1)
    if [ -n "$GOVET_ERRORS" ]
        then
            log_error "go vet failed for the following reasons:
            $GOVET_ERRORS
please run 'go vet $*' on your changes before committing."
        exit 1
    fi
}

run_gotest() {
    GOTEST_OUTPUTS=$(go test "$*" 2>&1)
    GOTEST_ERRORS=$(echo "$GOTEST_OUTPUTS" | grep "FAIL")
    if [ -n "$GOTEST_ERRORS" ]
        then
            log_error "go test failed for the following reasons:
            $GOTEST_OUTPUTS
please run 'go test $*' on your changes before committing."
        exit 1
    fi
}

echo "Run go vet"
run_govet "github.com/snower/slock/server"
run_govet "github.com/snower/slock/client"

echo "Run go test"
run_gotest "github.com/snower/slock/server"
run_gotest "github.com/snower/slock/client"

echo "Run Benchmark"
export PATH=$(pwd):$PATH

slock > /dev/null 2>&1 &

SLOCK_PS=$(ps aux | grep slock | grep -v grep)
if [ -z "$SLOCK_PS" ]
    then
        $SLOCK_ERRORS = $(slock 2>&1)
        log_error "slock start failed for the following reasons:
                   $SLOCK_ERRORS
please run 'slock' on your changes before committing."
    exit 1
fi

BENCH_OUTPUTS=$(timeout 120 go run benchmarks/benchmark/benchmark.go --client=16 --conc=64 --count=100000 2>&1)
BENCH_SUCCEDS=$(echo $BENCH_OUTPUTS | grep "Succed")
if [ -z "$SLOCK_PS" ]
    then
        log_error "slock benchmark failed for the following reasons:
                   $BENCH_OUTPUTS
please run 'go run benchmarks/benchmark/benchmark.go' on your changes before committing."

    ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
    ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
    exit 1
fi

echo "Benchmark Info:
$BENCH_OUTPUTS
"

ps -ef | grep slock | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
ps -ef | grep benchmark | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1

exit 0