#绑定的IP地址，需要开启远程访问请修改为0.0.0.0
bind="127.0.0.1"

#绑定的端口地址
port=5658

#日志文件地址
log="/var/log/slock/slock.log"

#日志输出级别，默认INFO，可用参数DEBUG|INFO|Warning|ERROR
log_level="INFO"

#日志文件最大大小
log_rotating_size=67108864

#日志文件保留数量
log_backup_count=5

#日志缓冲区大小
log_buffer_size=0

#日志刷新时间
log_buffer_flush_time=1

#数据文件目录
data_dir="/var/lib/slock/"

#快速hash表大小，每个DB中通过LOCK Key查询锁信息时先查询此表，无锁冲突多核性能好
#内存充足时一般需配置为最大加锁数量十倍可大幅提高并发性能
db_fast_key_count=4194304

#并发队列数量
#每个并发队列拥有独立的超时、过期及持久化队列，值越大并发能力越强
db_concurrent=8

#AOF持久化超时时间，默认超过此时间为释放的锁会持久化，单位秒（S）
#设置合适时间可保证大量短时同步加锁请求会在此时间内完成，可大幅降低持久化压力，提高QPS
db_lock_aof_time=1

#AOF持久化为过期时间百分比值
#Lock操作时在exprid_flag中设置持久化为过期时间百分比标志位时生效
db_lock_aof_parcent_time=0.3

#AOF持久化缓冲队列大小
aof_queue_size=65536

#AOF持久化重写文件大小
aof_file_rewrite_size=67174400

#AOF持久化文件写缓冲区大小
aof_file_buffer_size=4096

#AOF持久化主从同步循环缓冲区初始值
aof_ring_buffer_size=4194304

#AOF持久化主从同步循环缓冲区最大值
aof_ring_buffer_max_size=268435456

#主从同步配置，如：192.168.0.2:5658
#设置表示配置follower模式，从该leader同步数据
slaveof=

#集群名称，配置值表示启用集权模式，此时忽略主从模式配置
replset=