name: BuildTest

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master, feature/* ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        go-version: [ '1.17', '1.19', '1.22', '1.23', '1.24']

    steps:
      - uses: actions/checkout@v2
      - name: Install redis-cli
        run: |
          sudo apt-get update
          sudo apt-get -y install redis
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Build
        run: go build
      - name: Test
        run: ./run-tests