name: BuildTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install redis-cli
        run: |
          sudo apt-get update
          sudo apt-get -y install redis
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: [ '1.17', '1.19', '1.21', '1.22']
      - name: Build
        run: go build
      - name: Test
        run: ./run-tests