name: BuildTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build1-12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.12

    - name: Build
      run: go build

    - name: Test
      run: ./run-tests

  build1-14:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Build
        run: go build

      - name: Test
        run: ./run-tests

  build1-17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build

      - name: Test
        run: ./run-tests

  build1-18:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: go build

      - name: Test
        run: ./run-tests

  build1-19:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: go build

      - name: Test
        run: ./run-tests